### ISSUE TITLE
How to define H0?

### ISSUE THREAD

**Issue by ghost** [Luckick/EAGCN#4]
I read your paper, but I don't know how to define initial H.
Is it 0 or not?

**Comment by Luckick** [comment]
H_0 = X
Which means the original node feature extracted by RDKit, the detail contents are described in following table:
![image](https://user-images.githubusercontent.com/12540789/39962494-07d9e29c-561e-11e8-91f7-6784b20810ea.png)
which is consistent with the paper we cited: Convolutional embedding of attributed molecular graphs for physical property prediction.

**Comment by ghost** [comment]
Thank you for your nice describing !
I understand H_0 now and I'll read Convolutional embedding of attributed molecular graphs for physical property prediction !
