### ISSUE TITLE
[Question] Input data

### ISSUE THREAD

**Issue by laifi** [Luckick/EAGCN#5]
Hello ,
I am trying to use this EAGCN with my data ,composed of set of triples ( entity,relation,entity)
The entities (text data) are featurized with word2vec model embedding ( 100 feature/node )
Please , any help of how should the input data looks like , i cannot find any documentation about that !

**_Thank you !_**

**Comment by WhisperWind22** [comment]
I am not author, but i'll try to answer.

You can see required input in models.py in forward function https://github.com/Luckick/EAGCN/blob/master/eagcn_pytorch/models.py#L111
The model require in input 7 matrices. 
adjs is adjacency matrix with ones on main diagonal.
afms is matrix with features of nodes
the remaining 4 matrices bfts, OrderAtt, AromAtt, ConjAtt, RingAtt are matrices with features of edges

**Comment by Luckick** [comment]
WhisperWind22 is right. 
You may need to revise the code when you have different number of relations. (We have 5 different relations so we use bfts, OrderAtt, AromAtt, ConjAtt, RingAtt to represent them.) 
For the building of those tensors, you may refer to neural_fp.py
