### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by QWQyyy** [Luckick/EAGCN#6]
(EAGCN2) D:\PycharmProjects\pythonProject\EAGCN\eagcn_pytorch>python train.py
usage: train.py [-h] [--arch ARCH] [--molfp FP] [--rs RS] [-b N] [--dr DR]
                [--print-freq N] [-t EVAL_TRAIN_LOADER]
                dataset
train.py: error: the following arguments are required: dataset

我想知道作者这个到底是什么设计，在您的readme.md中没有任何说明？

**Comment by Luckick** [comment]
Please check the updated version. 
Or simply add a dataset name, e.g. python train.py freesolv

**Comment by QWQyyy** [comment]
> 请检查更新的版本。 或者简单地添加一个数据集名称，例如 python train.py freesolv

fine, thanks
